### ISSUE TITLE
Documentation: Interop with non-react-reason components

### ISSUE THREAD

**Issue by pckilgore** [kMeillet/reasonml-code-split#79]
Thanks for the module!

One of my requirements is to interop well with a preexisting components library written in standard ReactJs, transpiled with Babel, linked with Lerna in our monorepo.

It took some difficulty to work out how to do that with this library, so I wanted to share.  Now, admittedly, I'm new to react-reason so this might be a bad pattern. But it compiles cleanly and works:

```reason
module type T = {
  let make: {. "message": string} => React.element;

  [@bs.obj]
  external makeProps:
    /* Type the props for your imported component here. */
    (~message: 'message, ~key: string=?, unit) => {. "message": 'message} =
    "";
};

[@bs.val] external component: (module T) = "undefined";

module Lazy: T = {
  include (val component);
  /* make sure your import()ed component is a default export! */
  let make =
    ReLoadable.lazy_(() => DynamicImport.import("@internal/a-component"));
};
```
Note the final `let default = make;` in the module definition does not seem to be necessary with this pattern, as you can see by the generated bs.js:
```js
// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

var make = React.lazy((function (param) {
        return import("@internal/a-component");
      }));

var Lazy = /* module */[/* make */make];

export {
  Lazy ,
  
}
/*  Not a pure module */
```

Happy to include a PR with derived documentation, if you think it helpful, and I'd love any suggestions on how to use less boilerplate.

**Comment by pckilgore** [comment]
After some iteration I realized there are some helpers to more idiomatically generate the code I was writing manually above.

Now my files take the form:

```reason
module type T = {
  [@react.component]
  let make: (~name: string) => React.element;
};

[@bs.val] external component: (module T) = "undefined";

module Lazy: T = {
  include (val component);
  /* make sure your component is a default export! */
  let make =
    ReLoadable.lazy_(() => DynamicImport.import("@internal/a-component"));
};
```

Which begs the question:  How does one write their own `[bs.XXXX]` annotation (macro? not great with the terminology yet).

**Comment by arialpew** [comment]
Hi.

From what I see, this concerns JSX v3.

Feel free to make a pull request for documentation update 👍  . Second example is really nice.

I will work on a similar pattern for JSX v2 component (import non-ReasonReact component).

About macro, i think you can't write your own [@bs] macro (bound to compiler-land ?). Hard to find info on this topic :/ . Maybe PPX [%] (bound to user-land ?) will fit your use case : https://github.com/shrynx/awesome-ppx-reasonml

I don't know what's the limit of macro in Ocaml/ReasonML, but codegen can avoid a lot of boilerplate code (ie : auto-generate Lazy component from annotation). A must have for developer experience and for large application.

**Comment by pckilgore** [comment]
Yeah, I'll put the ppx idea on a shelf for now,  It seems like PPX are a
bit discouraged by the reason docs.  Docs PR when I get a minute.

**Comment by arialpew** [comment]
I wrote the documentation about this problem, if you think you have to add more information do not hesitate to do a PR. ;) 

https://github.com/kMeillet/reason-loadable/commit/5d232510c633c34c4a28b01b3eca953096376f01

**Comment by pckilgore** [comment]
Thanks! Sorry I forgot about this.
