### ISSUE TITLE
When using this in a project with reason-react v0.8.0, this libraries reliance on v0.7 causes v0.7 to be used globaly

### ISSUE THREAD

**Issue by JasoonS** [kMeillet/reasonml-code-split#84]
When I used this library in a project with react v0.8 I got the following message from the bsb compilor:

![image](https://user-images.githubusercontent.com/6032276/82682321-5e7fba80-9c4f-11ea-97b4-57a15c522161.png)

And my whole project ends up using v0.7 instead of v0.8.

I can test the upgrade of this and make a PR if you want?

**Comment by arialpew** [comment]
I'll release an update tonight to solve this issue #84 and #83 .

**Comment by arialpew** [comment]
Fixed in reason-loadable@1.0.0 : https://github.com/kMeillet/reason-loadable/releases/tag/1.0.0

**reason-react** is now a peerDependency and we use a more relax version (>= instead of ^).

**Comment by JasoonS** [comment]
Thanks!
